apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyseplus-admin
  labels:
    app: wyseplus-admin
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wyseplus-admin
  template:
    metadata:
      labels:
        app: wyseplus-admin
    spec:
      containers:
        - name: wyseplus-admin
          image: 290223772942.dkr.ecr.ap-south-1.amazonaws.com/wyseplus-admin:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
